### ISSUE TITLE
kdwsdl2cpp generates wrong code

### ISSUE THREAD

**Issue by SudakovIvan** [KDAB/KDSoap#118]
Problematic part of the WSDL:
<xs:complexType name="angleLandMarkType">
<xs:complexContent>
<xs:extension base="ns1:objectType">
<xs:sequence>
<xs:element name="source" type="xs:string" minOccurs="0"/>
</xs:sequence>
<xs:attribute name="a" type="xs:double" use="required"/>
<xs:attribute name="b" type="xs:double" use="required"/>
**<xs:attribute name="d" type="xs:double"/>**
</xs:extension>
</xs:complexContent>
</xs:complexType>

Generated code:
class __AngleLandMarkType::PrivateDPtr : public QSharedData
{
public:
    PrivateDPtr();

public:
    QString mSource;
    bool mSource_nil;
    double mA;
    double mB;
    double d;
    bool mD_nil;
};

void __AngleLandMarkType::setD( double _d )
{
    **d_ptr->d_nil = false**;// converter_complextype.cpp:300
    d_ptr->d = _d;
}

Error: d_nil - there is no such member in the class

I found a strange code in the MemberVariable::memberVariableName() method:
else if ( name == QLatin1String("q") || name == QLatin1String("d") ) {
      n = name;

**Comment by dfaure-kdab** [comment]
(Looks like I completely missed this bug report, sorry about that).

The "strange code" is about the pimpl pattern, often implemented by a "d" pointer, called "d" and not "mD".
But clearly there's a bug that the _nil should be passed as input to memberVariableName, not just appended to the other variable name.

Reproduced, will fix.
