### ISSUE TITLE
Possible loss of time-zone information from KDDateTime arguments

### ISSUE THREAD

**Issue by rokm** [KDAB/KDSoap#123]
As a work-around to #122, one may try to construct a KDDateTime object and explicitly set its timezone via KDDateTime::setTimeZone() method. However, this information may get lost when object is passed to a remote-method call request:

```c++
#include <KDSoapClient/KDSoapClientInterface.h>
#include <KDSoapClient/KDDateTime.h>

#include <QtCore>

int main (int argc, char **argv)
{
    QCoreApplication app(argc, argv);

    // Current time in local time-zone
    KDDateTime currentLocal(QDateTime::currentDateTime());

    // Current time in UTC
    KDDateTime currentUtc(QDateTime::currentDateTimeUtc());
    currentUtc.setTimeZone("Z");

    // Dummy request
    KDSoapMessage request;

    KDSoapValueList data;
    data.addArgument("TimeStampL", currentLocal);
    data.addArgument("TimeStampU", currentUtc);

    request.addArgument("Data", data);

    // Call remote method
    // Set up test end-point: nc -l 8080
    KDSoapClientInterface iface("http://localhost:8080", "test");
    KDSoapMessage response = iface.call("TestRequest", request);

    return 0;
}
```

Running the above example (compiled with Qt5) results in the following request:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <n1:TestRequest xmlns:n1="test">
      <Data>
        <TimeStampL>2018-03-29T21:15:04.874</TimeStampL>
        <TimeStampU>2018-03-29T19:15:04.874</TimeStampU>
      </Data>
    </n1:TestRequest>
  </soap:Body>
</soap:Envelope>
```

As can be seen, the explicitly-set time-zone string was lost. The issue here is that KDSoapValueList::addArgument() will implicitly construct a QVariant, and in the above example, it will use the QVariant::QVariant(const QDateTime &) constructor. So the variant actually stores a QDateTime, and during serialization goes through the following case:
https://github.com/KDAB/KDSoap/blob/57cccea63c21c96fd530cc039f30f1e121d203b7/src/KDSoapClient/KDSoapValue.cpp#L179
which constructs a new KDDateTime object without time-zone information.

The above issue is avoided by explicitly constructing QVariant:
```c++
    data.addArgument("TimeStampU", QVariant::fromValue(currentUtc));
```

and could be addressed in the library by providing an overload of KDSoapValueList::addArgument() for KDDateTime, which would take care of explicit QVariant construction.

**Comment by dfaure-kdab** [comment]
The problem is that such overloads would have to be added in `KDSoapValue::addArgument`, `KDSoapMessage::addArgument`, `KDSoapValue` constructor.... anywhere where a value is passed as `QVariant`.

I think it would be better to provide a conversion operator to `QVariant` in `KDDateTime`.
Do you want to try that and submit such a patch as a merge request if it works out?

**Comment by rokm** [comment]
Adding a conversion operator to ```QVariant``` does indeed seem to fix the issue as well. I'll open a pull request.
