### ISSUE TITLE
Generate server and client stubs in one class?

### ISSUE THREAD

**Issue by uteichert** [KDAB/KDSoap#136]
Hi,

while working on a real-world application, I needed the client and the server stubs generated out of one WSDL file. I did not found an option to generate one class with both stubs, so I generated them separately. However, this leads to a lot of code duplication, because the server and client classes do not share a base class and generated types are different classes although they originate from the same definition.

Did I simply miss an option in kdwsdl2cpp? Or is this just one of the corner cases which nobody but me hits ;-?

TIA,
Uli

**Comment by dfaure-kdab** [comment]
I haven't seen this request before, because typically the client and the server are separate programs.
I can see how it might happen that the same program wants to do both though (e.g. if chaining them, or because the program is generic).

I don't recall that there is an option for this right now, but patches welcome, it should be easy to add (one option and one if statement, I think)

**Comment by uteichert** [comment]
OK, I'll give it a try. On a related note, I once had problems with a quite complicated WSDL, which I only got solved by adding debugging output to kdwsdl2cpp, complete with command line option to switch it on and off. Would that be interesting, too?

**Comment by dfaure-kdab** [comment]
With Qt5 there's no need for a command-line option for that, there's qCDebug and qtlogging.ini and $QT_LOGGING_RULES. But KDSoap is still Qt4 compatible so we can't use any of this, hmm.

I guess having our own switch for that debug output isn't a bad idea then, it's not worth dropping Qt4 compat for.

**Comment by uteichert** [comment]
I just found out that kdwsdl2cpp creates server and client stubs when -server is given. This code
in converter.cpp:
```c++
bool Converter::convert()
{
    convertTypes();
    //  mNSManager.dump();
    if (Settings::self()->generateServerCode()) {
        convertServerService();
    }
    return convertClientService();
}
```
generates both in that case. I guess that only calls for a documentation update then...

**Comment by uteichert** [comment]
Hi,
thanks for merging the -help-on-missing patch,

CU,
Uli
