### ISSUE TITLE
wsnt:Topic value lost WSNT__Notify::deserialize(_request)

### ISSUE THREAD

**Issue by DRFrederik** [KDAB/KDSoap#141]
When generating onvif event stubs:
kdwsdl2cpp -namespace events_ver10 -o events_ver10.h -server https://www.onvif.org/ver10/events/wsdl/event.wsdl
kdwsdl2cpp -namespace events_ver10 -impl events_ver10.h -o private/events_ver10.cpp -server https://www.onvif.org/ver10/events/wsdl/event.wsdl

Using event_ver10.cpp
in function:
void events_ver10::NotificationConsumerBindingServiceServerBase::processRequest( const KDSoapMessage &_request, KDSoapMessage &_response, const QByteArray& _soapAction )

comment the line notify(notify);

Given the following onvif soap message:
...
<wsnt:NotificationMessage>
	<wsnt:Topic
        Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">
        tns1:Device/Trigger/DigitalInput
	</wsnt:Topic>
	<wsnt:Message>
		<tt:Message
            UtcTime="2018-10-05T15:14:01Z"
            PropertyOperation="Initialized">
			<tt:Source>
				<tt:SimpleItem
                    Name="InputToken"
                    Value="1"/>
			</tt:Source>
			<tt:Data>
				<tt:SimpleItem
                    Name="LogicalState"
                    Value="true"/>
			</tt:Data>
		</tt:Message>
	</wsnt:Message>
</wsnt:NotificationMessage>
...
Looking at the data of KDSoapValue::Private that reflects wsnt:Topic (this data can be found in the KDSoapMessage &_request), we have:
m_name "Topic"
m_nameNamespace "http://docs.oasis-open.org/wsn/b-2"
m_value QVariant(QString, "tns1:Device/Trigger/DigitalInput")
m_typeNamespace ""
m_typeName ""
m_qualified false
m_nillable false

The KDSoapValue with name "Topic" is a child value of "NotificationMessage" as reflected by the xml.
In the generated function events_ver10::NotificationConsumerBindingServiceServerBase::processRequest, we have:
notify.deserialize(_request)
This bring us to:
void events_ver10::WSNT__TopicExpressionType::deserialize( const KDSoapValue& mainValue )

give our Topic message:
	<wsnt:Topic
        Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">
        tns1:Device/Trigger/DigitalInput
	</wsnt:Topic>
We have no parsing of the topic value item even though it is present in the KDSoapMessage:
m_value QVariant(QString, "tns1:Device/Trigger/DigitalInput")
This value goes lost when "deserializing" the KDSoapValue into WSNT__TopicExpressionType, making this type useless.
I see no reason why this value is not parsed and stored into WSNT__TopicExpressionType. Someone should look into the generator code.

**Comment by dfaure-kdab** [comment]
`events_ver10::WSNT__TopicExpressionType::deserialize` sets `d_ptr->mAny` for each of the child values.

For reference, the XSD for that type says
```
  <xsd:complexType name="TopicExpressionType" mixed="true">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="1" processContents="lax" />
    </xsd:sequence>
    <xsd:attribute name="Dialect" type="xsd:anyURI" use="required" />
    <xsd:anyAttribute/>
  </xsd:complexType>
```
So there can be only one child value, good.

You can get your topic by calling `events_ver10::WSNT__TopicExpressionType::any()` and deserializing that KDSoapValue by calling `events_ver10::WSTOP__Topic::deserialize()` --- assuming you know for sure it's a Topic.

This is the price of the flexibility given by `<any>`...
