### ISSUE TITLE
why faultCode is expected by number? 

### ISSUE THREAD

**Issue by postrstk** [KDAB/KDSoap#166]
When the lastErrorCode method is generated, the string is 
```C++ 
code + = "return d_ptr->m_lastReply.childValues().child(QLatin1String(\"faultcode\")).value()toInt();";
``` 
however, the faultCode is a string by standard (http://www.tutorialspoint.com/soap/soap_fault.htm).

**Comment by dfaure-kdab** [comment]
Good point. We use ints for HTTP errors, but indeed this should be a string in general.
We can't change the signature of the existing method, but I'll add another one, lastFaultCode.
