### ISSUE TITLE
Ambiguous class names when using a non-empty Qt Namespace

### ISSUE THREAD

**Issue by DarioSamo** [KDAB/KDSoap#171]
As shown in this commit in my fork here:
https://github.com/DarioSamo/KDSoap/commit/69118cd6727668bb544251d8e2dc53c6d5cf73bb

kdwsdl2cpp/schema/parser.h and src/KDSoapServer/KDSoapServerObjectInterface.h use forward declarations for QUrl and QAbstractSocket that are not using the Qt namespace macros, causing ambiguous class names errors in VS 2017.

I've not created a pull request with this specific fix as I'm not aware if it's preferable to just include the headers for these classes instead.

**Comment by dfaure-kdab** [comment]
This commit looks good, please make a merge request.

I admit that I'm not testing KDSoap with a namespaced Qt. I wouldn't be surprised if you found more issues.

**Comment by DarioSamo** [comment]
Excluding the tests, this is the only compilation issue I've found so far.

Some of the tests fail to compile due to this: https://github.com/KDAB/KDSoap/issues/89

But it's something that we can easily work around for now.
