### ISSUE TITLE
SOAP over UDP

### ISSUE THREAD

**Issue by caspermeijn** [KDAB/KDSoap#175]
Hi, I am building a [library](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client) to do [WS-Discovery](http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html). For this I need to support sending and receiving [SOAP over UDP](http://docs.oasis-open.org/ws-dd/soapoverudp/1.1/os/wsdd-soapoverudp-1.1-spec-os.html). I got this working by including KDSoapMessageReader_p.h and KDSoapMessageWriter_p.h for the KDSoap sources. These classes are exported for the KDSoapServer library, but are not part of the official api.

I see three ways to make this work properly:
1. Make the classes part of the public api.
2. Add a QUdpSocket wrapper, which can send and receive KDSoapMessages (something like [this](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client/blob/master/src/soapudpclient.h)).
3. Create a new [Binding type](https://github.com/KDAB/KDSoap/blob/master/kdwsdl2cpp/wsdl/binding.h#L45) and let kdwsdl2cpp generate a UDP services.

I think it is unwanted to export the internal apis KDSoapMessageReader and KDSoapMessageWriter. And I think 3 is a bit overkill as I think WS-Discovery will be the only user of UDP. I think 2 is the best solution.

What do you think about this? Would you accept something like [SoapUdpClient](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client/blob/master/src/soapudpclient.h)? Or would you prefer a different solution to this problem?

**Comment by dfaure-kdab** [comment]
I agree with your analysis.

SoapUdpClient, conceptually, has the same problem as the generated Service classes, the problem solved by the Job classes: when the signal receivedMessage is emitted, you don't know which message this is a reply to. But maybe with UDP that's actually fine anyway, there aren't any replies, just messages going back and forth without context? I'm not sure (but if that's the case, then indeed I would accept something like SoapUdpClient).
The argument name "replyMessage" in both the signal and the send method is certainly confusing to me, possibly wrong in both?

Do you have a specific interest in the whole of WS-Discovery implementation to be in your separate library, or would it make sense to make it part of KDSoap so that other KDSoap users also get WS-Discovery support? By this I mean, surely there is one layer above SoapUdpClient?

**Comment by caspermeijn** [comment]
> SoapUdpClient, conceptually, has the same problem as the generated Service classes, the problem solved by the Job classes: when the signal receivedMessage is emitted, you don't know which message this is a reply to. But maybe with UDP that's actually fine anyway, there aren't any replies, just messages going back and forth without context? I'm not sure (but if that's the case, then indeed I would accept something like SoapUdpClient).

SOAP-over-UDP defines two modes: one-way and request/response. It uses WS-Addressing for marking the sender and recipient. The RelatesTo header of the response is supposed to be the message-id of the request, however simple WS-Discovery implementations don't adhere to this. They just send the static message whenever they receive a message containing the word Probe. Therefore I don't look at the RelatesTo header and use another field for de-duplication.

In [kdsoap-ws-discovery-client](https://gitlab.com/caspermeijn/kdsoap-ws-discovery-client) I have a class that takes all ProbeMatches and then filters for those that actually match the requested Probe. This is needed as not all implementations are compliant.

> The argument name "replyMessage" in both the signal and the send method is certainly confusing to me, possibly wrong in both?

I think this was just a copy-paste. This should have better names. I am planning to add some documentation to the headers as well.

> Do you have a specific interest in the whole of WS-Discovery implementation to be in your separate library, or would it make sense to make it part of KDSoap so that other KDSoap users also get WS-Discovery support? By this I mean, surely there is one layer above SoapUdpClient?

The primary reason it is now a separate library is that it is still in development and that I like it to be GPL. I think this would fit well in the KDSoap repository eventually. 

However I am not sure what happens to the license of the binary when it includes the WS-Discovery WSDL file. I think it won't be GPL anymore as the WSDL file states that it may not be modified. Do you have experience with GPL library with proprietary WSDL?

**Comment by dfaure-kdab** [comment]
Good question about the licensing, I never encountered this case before.
I'm afraid I don't know the answer, you'd have to ask a lawyer or the FSF (or possibly there are forums for such questions?)...
The WSDL file is certainly considered a source file in this case since we generate code from it.
