### ISSUE TITLE
[1.8.0] kdwsdl2cpp generates invalid code

### ISSUE THREAD

**Issue by tuxmaster5000** [KDAB/KDSoap#179]
QList's without type will created.
The wsdl file can received [here](https://pki.pca.dfn.de/dfn-ca-global-g2/cgi-bin/pub/soap?wsdl=1).
The output of kdwsdl2cpp are here attached
[code.zip](https://github.com/KDAB/KDSoap/files/3499864/code.zip)

.

**Comment by dfaure-kdab** [comment]
Interesting. Normally people write
`<attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:string[]"/>`
but this WSDL file says
`<attribute ref="soapenc:arrayType" wsdl:arrayType="soapenc:string[]"/>`
which leads to `ERROR: basic type not found: "soapenc:string"`
I see that soapenc does define string though, so this is indeed a bug in KDSoap.

**Comment by dfaure-kdab** [comment]
Fixed
