### ISSUE TITLE
URLs changed to HTTPS

### ISSUE THREAD

**Issue by caspermeijn** [KDAB/KDSoap#199]
@winterz You changed http links to https in commits a81d8dfa704b6ba7cd55ce8b38ba318e5fc07571 and b404603a28c67b0cb0f14a6dbee9cf3cd66d1a65. However you also changed some namespace URLs. I think that is incorrect. I believe that these URLs should match exactly and these should not be used in a browser.

**Comment by winterz** [comment]
you're right.  I went too far.  my intention was to change the urls in the comments only.
I'll undo some of the changes.

**Comment by winterz** [comment]
@caspermeijn please review 56fd2ade939baac43a2a303132c620587b5496bf
let me know.

**Comment by caspermeijn** [comment]
Looks good to me, thanks
