### ISSUE TITLE
URI in XSD enumeration leads to failure

### ISSUE THREAD

**Issue by phieber** [KDAB/KDSoap#20]
KDSoap converts the following XSD enum to an invalid C++ syntax

\<xsd:simpleType name="ParameterName"\>
    \<xsd:restriction base="xsd:string"\>
      \<xsd:enumeration value="http://f.q.d.n/ext/enum0" /\>
      \<xsd:enumeration value="http://f.q.d.n/ext/enum1" /\>
      \<xsd:enumeration value="http://f.q.d.n/ext/enum2" /\>
    \</xsd:restriction\>
\</xsd:simpleType\>

leads to

enum Type { Http_//f.q.d.n/ext/enum0, Http_//f.q.d.n/ext/enum1,  Http_//f.q.d.n/ext/enum2 }; //syntax error!

**Comment by Knarf64** [comment]
Fixed in 2d4eadb0fc346d84e68886ebc6c26c0070b0fab1
Sorry to notice that late. 
Regards.
