### ISSUE TITLE
libkode uniformization with kode

### ISSUE THREAD

**Issue by martonmiklos** [KDAB/KDSoap#201]
I have opened this issue to discuss if it would be useful to bring the two copies of libkode (one in KDSoap and one in the kode) under one hood.  I have some ideas to implement in kode which might be beneficial to add to the KDSoap  as well.

My recommendation would be the following:
- Agree on a common coding style
- Reformat the KDSoap's libkode according to that format
- Move the the libkode from KDSoap to a separate git repository under the governance of KDAB (since it is business critical here), and add it to the KDSoap as a git submodule
- I will replace the kode's libkode with that repo and work on that until it work with it as a submodule.  It will result some PRs to the common repo, which will needs some reviewing resources. 

I know it is going to be a tedious task, and will require efforts on KDAB side as well but manually merging kode changes would be tedious as well ;).

Thank you for your feedback in advance!

**Comment by dfaure-kdab** [comment]
Wouldn't it be a problem for Cornelius to have kode depend on a KDAB repository (especially when libkode is originally *not* KDAB's code)? Or did you officially take over maintenance of kode by now? I'm not sure about the decision process on you guys' side, but Cornelius is a good friend, I don't want to alienate him :)

Just wondering if the other way around would make more sense (KDSoap having a non-KDAB-hosted libkode submodule). The "business critical" aspect being mitigated by the fact that submodule updates aren't automatic, we can test if everything still works before pointing to a new revision.
One reason for that would be that I don't end up with all libkode review requests :-)

**Comment by martonmiklos** [comment]
Thank you for your answer David! I have not taken over the maintenance because I have not felt my skills good enough for that task. 

Over the last years I had to realize that there is a huge pit between "patching something in kode which makes it capable to perform a specific task" and writing proper code which meets a certain quality standards. Also I tended to mess up things in git, but I am constantly getting better on that.

I am interested in expanding the capabilities of both kode/kxml_compiler/libkode and KDSoap, but I would like to get my contributions reviewed by someone before going upstream. This is why I thought that moving the libkode under your umbrella would be a good point. kode is up for [adoption](https://github.com/cornelius/kode/blob/master/ADOPTME.md) for a while and I did not seen anyone else other than you and Cornelius doing reviewing around that code in the last couple of years. 

But the other way (just separating the libkode) what you mentioned seems to be reasonable for me as well.

Anyway I would love to hear @cornelius option on this.

> we can test if everything still works before pointing to a new revision.

One of the first of my medium term goals with kode  (after we pass through the code style and libkode migration) is making the unit tests working again both with cmake and qmake, and setup the Travis CI verification. If we are at this point we could get the KDSoap unittests built and run in the libkode CI as well which could be a first level of barrier if I break something.

**Comment by cornelius** [comment]
Thanks for bringing this up and thanks for keeping me in the loop. I fully trust both of you to act as responsible maintainers for the code. Some discussion and peer review is certainly still helpful, though

I see that it could be helpful to have libkode in a separate repository. This would make it easier to reuse in different projects. This could also help with making releases of just libkode if that is something we want. My feeling is that with the current usage it's simpler to just submodule the code, though.

Releases of just libkode could also be done from the big repo. Not sure if it's worth the effort. Would this be something which helps you or would you prefer using the code as a submodule anyway?

I would support moving libkode to a separate repository. Where this is and who maintains it is secondary to me. If we don't want to change the status quo in terms of maintainership, I could just move the code to a separate repo and give both of you access there just as with the kode repo.

What do you think?

**Comment by dfaure-kdab** [comment]
A libkode separate repo that KDSoap can use as a git submodule, sounds good to me.

This is simpler for us and for our users compared to using releases.

**Comment by martonmiklos** [comment]
I also prefer the submodule approach for now. 

I think we agreed on using the Qt coding style as a common coding style, so it would be useful to define the next steps:
 - Create a new repository from the KDSoap's kode version. I think that version received more commits since the separation. 
- Reformat it to match the Qt style
- I will reformat the rest of the kode's code to match the Qt style and setup a Github action to add sanity checking. This github action could be added to the common libkode repository as well.
- I will add the common libkode to my kode fork, and integrate the changes added to the kode's libkode since the separation. 
- I will submit these integrated changes to the common repo in the forms of separated PRs.
- Once all of these PRs reviewed and closed I will submit a PR to the kode which will use the common libkode as a submodule.

**Comment by cornelius** [comment]
Would you do the uniformization just for libkode itself, or would you also target the other parts such as the common or schema parts?

And where should we create the common repo? Parallel to the kode repo as https://github.com/cornelius/libkode?

Tests are an important part. Having automated tests on the common repo which ideally test the different usage scenarios so that it won't break KDSoap would be great.

**Comment by martonmiklos** [comment]
> Would you do the uniformization just for libkode itself, or would you also target the other parts such as the common or schema parts?


My goal would be to have all common code shared between kdsoap and kode to be in a common repository. (I have not been aware of the common schema and common folders).

> And where should we create the common repo? Parallel to the kode repo as https://github.com/cornelius/libkode?

That's fine for me. 

> Tests are an important part. Having automated tests on the common repo which ideally test the different usage scenarios so that it won't break KDSoap would be great.

Yeah I shame myself for doing any work on kode without adding proper tests.

**Comment by martonmiklos** [comment]
Hi folks!

I have adjusted the coding style in kode, also setup a github action for the clang-formatter.

@cornelius could you please create the common repo? (If @dfaure-kdab  does not have any objections on the location and other details :)

**Comment by cornelius** [comment]
@martonmiklos, @dfaure-kdab I have created the repo now at https://github.com/cornelius/libkode and added you as collaborators exactly as on the kode repository. Feel free to push the common code there. We can adjust it as needed. Let me know, if you need anything there.

**Comment by martonmiklos** [comment]
@cornelius many thanks for creating the repository!
I will add  the KDSoap's code to the repo and run a clang-formatter and setup the github action to check the correct formatting. Then I will submit a PR to KDSoap to utilize the new repo as submodule.

**Comment by dfaure-kdab** [comment]
Many thanks to both of you!
