### ISSUE TITLE
Public gpg key missing

### ISSUE THREAD

**Issue by tuxmaster5000** [KDAB/KDSoap#202]
The public key, which was used to sign the source code is missing.
No link etc. is present, where it can be found, for verifying the code.

**Comment by winterz** [comment]
can you try https://www.kdab.com/kdab-products.asc
I don't know where to advertise this location.  suggestions?

**Comment by tuxmaster5000** [comment]
I would say, in the Readme.md, so that it is shown direct in the front of the project.
But my first try to find it, was the footer of the company page https://www.kdab.com

**Comment by winterz** [comment]
Readme.md is a good idea . I'll also ask putting on the footer of www.kdab.com
can we close this now?

**Comment by tuxmaster5000** [comment]
I think yes.
Thanks

**Comment by winterz** [comment]
Readme.md is a good idea . I'll also ask putting on the footer of www.kdab.com
can we close this now?

**Comment by winterz** [comment]
I added the KDAB Product key to keys.openpgp.org
