### ISSUE TITLE
Weird license in WSDL unit test file

### ISSUE THREAD

**Issue by lbeltrame** [KDAB/KDSoap#207]
This came up when reviewing kdsoap for inclusion in openSUSE. A unit test has a strange, possibly incompatible license:

https://github.com/KDAB/KDSoap/blob/e6d44410e52ca0a78db76d613c3b2798a159b6b3/unittests/onvif.org/devicemgmt.wsdl#L6

Note the "No license is granted to modify this document."

**Comment by dfaure-kdab** [comment]
This is a copy of a WSDL file "found on the internet" in order to test that we generate correct C++ code from it. It's obviously not meant to be modified here, that would be rather pointless.

Is this really a blocker for inclusion in openSUSE?

It's just a unittest, it doesn't end up anywhere on the user's system.

**Comment by lbeltrame** [comment]
It's not a blocker, but trips the automated legal check, which means that a human must look at it, and that means from days to weeks before acceptance.

**Comment by ismail** [comment]
Well this is a legal problem because the files will end up in the source rpm.

**Comment by perezmeyer** [comment]
This would indeed be a problem if someone tries to get it into the Debian archive. It would have to be stripped for sure.

**Comment by dfaure-kdab** [comment]
OK if I change this so that the WSDL file is downloaded at build time? kdwsdl2cpp supports this mode of operation.

**Comment by Vogtinator** [comment]
Network access during build time breaks reproducibility and is thus blocked completely.

**Comment by rikmills** [comment]
Yes, Ubuntu (and I think) Debian builders are not allowed network access during the build. This is also for security reasons.

**Comment by jriddell** [comment]
Non free licences will cause problems for pretty much every distro.
Network access during build time is fine for a unit test which only optionally gets run, packagers can just ignore it.

**Comment by Vogtinator** [comment]
> Network access during build time is fine for a unit test which only optionally gets run, packagers can just ignore it.

Unless they want to run those optional unit tests, yes.

**Comment by perezmeyer** [comment]
Please assume we packagers want to run the tests. Sometimes we can't due to manpower (specially if tests are flaky or require an extensive setup) but we try to run them as part of the build process whenever possible.

**Comment by dfaure-kdab** [comment]
I'm trying to replicate the issues (for which those onvif unittests were added) into a wsdl file of my own, which will allow deleting the onvif tests. Tricky though.

**Comment by caspermeijn** [comment]
Most of the WSDL files don't have any copyright or licensing information at all. Is that also a problem for openSUSE?

And please note there are more files with wierd licenses. For example: unittests/soap_over_udp/wsdd-discovery-200901.wsdl and unittests/salesforce_wsdl/salesforce-partner.wsdl

**Comment by dfaure-kdab** [comment]
One step done in commit 4234096, more to come...

**Comment by dfaure-kdab** [comment]
Done, the text "No license is granted" doesn't appear anywhere anymore, in git branch kdsoap-1.9 (and master).

Please let me know if I can close this issue.

**Comment by lbeltrame** [comment]
Thanks, this is fixed. There's another problem that came up, but that warrants a separate issue.

**Comment by rikmills** [comment]
Would a new point release be possible now please, so distros do not have to mess around repacking the existing stable tar?

**Comment by winterz** [comment]
I'll try for a 1.9.1 release in the upcoming week

**Comment by winterz** [comment]
done.  1.9.1 is tagged and released.
