### ISSUE TITLE
EULA in source package

### ISSUE THREAD

**Issue by lbeltrame** [KDAB/KDSoap#212]
Now that the issue with the license of the tests is done, another issue came up during review in openSUSE, which is the EULA (`LICENSE.txt`) which is present in the repository, which I assume only affects the commercially-licensed version of KDSoap, because it mentions:

> By installing, copying, or downloading the Licensed Product, you agree
to be bound by the terms of this EULA

And of course the other provisions there which do not relate to the availability of the sources and the GPL/AGPL/LGPL licenses KDSoap uses. 

Again that raised a flag when reviewing this for openSUSE.  Can the source tarballs on GH be shipped without this EULA, or is there any other solution?

**Comment by tsdgeos** [comment]
Any reason this is a problem for KDSoap but not for GammaRay ?

**Comment by Vogtinator** [comment]
The GammaRay EULA seems significantly different.

For example, it states at the top `FOR COMMERCIAL VERSIONS`, but we don't ship the commercial version. This means it doesn't even apply (but IANAL).

The EULA here has: `By installing, copying, or downloading the Licensed Product, you agree
to be bound by the terms of this EULA.`. Later it even mentions license fees:

```Under the condition of Your payment of all license fees KDAB grants to
you a [...] license [...].

If you are an individual, you may install copies of the Licensed
Product on all of your computers provided that you are the only
individual using the Licensed Product.```

**Comment by tsdgeos** [comment]
Isn't the Readme clear enough?

```
License
KD Soap is (C) 2010-2020, Klaralvdalens Datakonsult AB, and is available under the terms of:
    the LGPL (except libkdsoap-server, see LICENSE.AGPL3-modified.txt)
    the GPL (except libkdsoap-server, see LICENSE.AGPL3-modified.txt)
    the KDAB commercial license, provided that you buy a license. please contact info@kdab.com if you are interested in buying commercial licenses.

Commercial licensing terms are available in the included file LICENSE.txt.
```

**Comment by lbeltrame** [comment]
We added the README to the licenses shipped with the openSUSE package to underline this fact. Thus, this can be closed.

**Comment by winterz** [comment]
Hi @lbeltrame 
I wonder if there's anything I can do/change to help make this more clear.
Let me know and I'll have a go at it.
-Allen

**Comment by lbeltrame** [comment]
Adjusting the EULA like the one mentioned in this thread, where it states that it is for commercial versions, would be useful in the long run.

**Comment by winterz** [comment]
> The GammaRay EULA seems significantly different.
> 
> For example, it states at the top `FOR COMMERCIAL VERSIONS`, but we don't ship the commercial version. This means it doesn't even apply (but IANAL).

No it does not.  you must be looking at an older GammaRay.
The Readme's and License.txt files of GammRay and KDSoap (and KDChart) are consistent
Nevertheless, it wouldn't hurt to spell this out more clearly at the top of License.txt

**Comment by winterz** [comment]
added "FOR COMMERCIAL VERSIONS" to License.txt in 60d46bb8a735ba0fb2f6aa5ee750699da9f42658
