### ISSUE TITLE
[question] xsd to cpp generator (without any wsdl)

### ISSUE THREAD

**Issue by kcris** [KDAB/KDSoap#213]
Hi,

is there a tool in kdsoap which allows generating c++ code from xsd only? (without using wsdl)

something similar to `kxml_compiler` ?

(which is part of the original kode repo, where libkode was initially developed too)
https://github.com/cornelius/kode/tree/master/kxml_compiler

does `kdwsdl2cpp` allow something like that?

thanks

**Comment by martonmiklos** [comment]
AFAIK there is no such a feature in kwsdl2cpp, but kxml_compiler was built for that job.

**Comment by dfaure-kdab** [comment]
Is there any reason not to use `kxml_compiler` for this job then? In other words, can I close this request because `kxml_compiler` does this just fine? Or is there a good reason to suggest that `kdwsdl2cpp` should have the option of doing this?

**Comment by kcris** [comment]
As far as I remember, I had tried `kxml_compiler`, I had failed to generate code for my schemas so I was just hoping to find an alternative here.
I think `kxml_compiler` was not able to recursively load my schemas, not via http nor locally
