### ISSUE TITLE
No-SSL support

### ISSUE THREAD

**Issue by anoymouserver** [KDAB/KDSoap#220]
Is it still intended that KDSoap works without SSL support?
If this is the case, the kdwsdl2cpp needs additional checks for `QT_NO_SSL`.

For example here:
https://github.com/KDAB/KDSoap/blob/e0c632f2cdcb0ca23791be5d8a231d8eae7992af/kdwsdl2cpp/src/main.cpp#L293-L299

I've also noticed that currently `QT_NO_OPENSSL` is used elsewhere, but Qt5 seems to use `QT_NO_SSL`.

**Comment by dfaure-kdab** [comment]
If you need KDSoap to work without SSL support, I will gladly review a patch for git master that adds QT_NO_SSL in the right places.

We just dropped Qt4 support so this is simpler to do now, you can turn all the QT_NO_OPENSSL into QT_NO_SSL and add the missing QT_NO_SSL ifdefs.

**Comment by SudakovIvan** [comment]
Will you make a patch as David said?

**Comment by SudakovIvan** [comment]
Thanks! Awaiting for merge...
