### ISSUE TITLE
Question: LGPL licensing

### ISSUE THREAD

**Issue by mridoni** [KDAB/KDSoap#223]
Hello, the README states:
_KD Soap is (C) 2010-2020, Klaralvdalens Datakonsult AB, and is available under the terms of:
the LGPL (**except libkdsoap-server**, see LICENSE.AGPL3-modified.txt)_

But if I open KDSoap/src/KDSoapServer/KDSoapServer.cpp, I find:
_** This file may be distributed and/or modified under the terms of the
** GNU Lesser General Public License version 2.1 and version 3 as published by the
** Free Software Foundation and appearing in the file LICENSE.LGPL.txt included._

I guess there is something eluding me, but I don't know how to reconcile the two things.

Thanks

**Comment by dfaure-kdab** [comment]
You are right. I'll look into changing the copyright headers in the server subdirectory to say AGPL.
While at it I'll use SPDX license markers...

**Comment by dfaure-kdab** [comment]
Actually it's AGPL-with-linker-clause (hence "modified" in the filename) so the SPDX license marker would add some confusion.
I'll just update the text.
