### ISSUE TITLE
[kdwsdl2cpp]Allow generating only sync/async client implementation

### ISSUE THREAD

**Issue by martonmiklos** [KDAB/KDSoap#224]
I was wondering if it would be useful to add a command line switch to the kdwsdl2cpp which would allow the users to generate client codes which contains only synchronous or asynchronous implementations. 

This could result smaller generated code, and would prevent calling a sync call by a mistake instead of an async (like I did just now). 

If you like the idea please let me know, it looks to be a low hanging fruit to implement for me.

**Comment by caspermeijn** [comment]
Personally I like this idea. 

1. The ONVIF WSDL take a long time to compile, I would assume that removing the sync code would speed that up by a factor of 2. 
2. When I first started using KDSoap I wasn't even aware of the async code as the sync code comes first in the generated headers. Maybe this could improve discoverability.

**Comment by martonmiklos** [comment]
> When I first started using KDSoap I wasn't even aware of the async code as the sync code comes first in the generated headers. Maybe this could improve discoverability.

Well, I had been walking in the same boot.

Meanwhile I was thinking about removing the async function prefix in the case if generating only async code to make the readability easier.

**Comment by dfaure-kdab** [comment]
I like the idea. However keep in mind that we generate *3* APIs, not 2:

sync methods
async methods
async jobs

The preferred one to use, except in unittests or command-line tools, is async jobs. It makes perfect sense to have a way to disable the other two. Or if you want to be thorough, allow enabling/disabling each one of the three independently.

**Comment by martonmiklos** [comment]
Btw. @dfaure-kdab is there any reason (other than historical) not utilising the QCommandLine features in the kdwsdl2cpp?

**Comment by dfaure-kdab** [comment]
Historical (QCommandLineParser didn't exist in Qt4).

I'm the (co-)author of QCommandLineParser BTW, so yeah, that's certainly not because it's no good :-)

Now that Qt4 is out, I'll happily review a port to QCommandLineParser :-)

**Comment by martonmiklos** [comment]
> The ONVIF WSDL take a long time to compile, I would assume that removing the sync code would speed that up by a factor of 2.

@caspermeijn FYI: the feature landed in KDSoap's master: feel free to test an regenerate your client codes.
