### ISSUE TITLE
Port away from QXmlSimpleReader

### ISSUE THREAD

**Issue by anoymouserver** [KDAB/KDSoap#231]
The QXmlSimpleReader is marked deprecated in Qt 5.15 and moved  to the `core5compat` module with Qt 6.0.
kdwsdl2cpp should probably be ported to QXmlStreamReader.

see also cornelius/libkode#22

**Comment by dfaure-kdab** [comment]
I did that in commit 90420647da6e7d3ee068a57e3964d5846b85d37c
