### ISSUE TITLE
No rule to make target 'kdwsdl2cpp', needed by wsdl .h

### ISSUE THREAD

**Issue by jorge-barroso** [KDAB/KDSoap#233]
Hi, I'm working on a dummy project using KDSOAP, when trying to compile my project I get the following issue:

```
/usr/bin/cmake --build /home/jorge/Documents/Projects/CLionProjects/StockExchangeUI/cmake-build-debug --target StockExchangeUI -- -j 9
make[3]: *** No rule to make target 'kdwsdl2cpp', needed by 'wsdl_ListStocks.h'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:123: CMakeFiles/StockExchangeUI_autogen.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/StockExchangeUI.dir/rule] Error 2
make: *** [Makefile:137: StockExchangeUI] Error 2
```

It's a Qt5 project and I've made sure the kdwsdl2cpp binary is available, here is my CMakeLists file in case it helps

```
cmake_minimum_required(VERSION 3.19)
project(StockExchangeUI)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

set(QT_VERSION 5)
set(REQUIRED_LIBS Core Gui Widgets Xml)
set(REQUIRED_LIBS_QUALIFIED Qt5::Core Qt5::Gui Qt5::Widgets Qt5::Xml)

find_package(Qt${QT_VERSION} COMPONENTS ${REQUIRED_LIBS} REQUIRED)

include(/usr/lib/cmake/KDSoap/KDSoapMacros.cmake)
include_directories(/usr/include/KDSoapClient /usr/include/KDSoapServer)

set(SRC main.cpp
        mainwindow.cpp
        mainwindow.h)

KDSOAP_GENERATE_WSDL(SRC wsdl/ListCurrencies.wsdl
        wsdl/ListStocks.wsdl)

add_executable(${PROJECT_NAME} ${SRC})
target_link_libraries(${PROJECT_NAME} ${REQUIRED_LIBS_QUALIFIED} kdsoap)
```

I'm running this on a standard manjaro with 3.19.1, any help would be appreciated

**Comment by dfaure-kdab** [comment]
You're not using the standard cmake way to "find" KDSoap.
Remove the `include()` and `include_directories()` lines, and instead do

    find_package(KDSoap CONFIG REQUIRED)

This will pick up /usr/lib/cmake/KDSoap/KDSoapConfig.cmake which will set up everything you need.
Then, instead of linking to `kdsoap`, link to `KDSoap::kdsoap` (google for "cmake imported targets" for more info)

**Comment by jorge-barroso** [comment]
This worked like a charm @dfaure-kdab , many thanks! Is this documented somewhere though? I looked on your examples and googled make find kdsoap but I found no results

**Comment by dfaure-kdab** [comment]
Now it is :) Thanks for the suggestion, I added this information in `INSTALL-cmake.txt` (which will soon replace `INSTALL.txt`, when we drop qmake). It's standard cmake, but it doesn't hurt to be explicit :)

(BTW we give cmake trainings, in case you're interested)
