### ISSUE TITLE
autogen.py: Still using Python 2?

### ISSUE THREAD

**Issue by jbglaw** [KDAB/KDSoap#238]
I was looking to get a recent snapshot built on an up-to-date system, but even the very first step, calling autogen.py, fails due to its dependency on Python 2. There was a ticket in 2013 (https://github.com/KDAB/KDSoap/issues/25) which mentioned this, nearly 8 years ago. Anything planned in that direction?

**Comment by dfaure-kdab** [comment]
Yes, the plan is to drop autogen.py and qmake altogether, and only use CMake, the support for which being already there.

Can I suggest using CMake instead?

**Comment by jbglaw** [comment]
I tried it and failed on target: I've got one remaining setup with a Qt 5.6 installation that won't come up (easily?) with `cmake`. Configuring with `cmake` requires a Qt 5.7+ installation, and it seems that running `autogen.py` etc. will happily accept that old Qt version. So it's not yet a complete alternative, but hopefully at some time, I'll get rid of that last 5.6 installation. So ... just a heads up here.

**Comment by winterz** [comment]
I cannot remember why we increased the min Qt version to 5.7.  this was done in July 2020

you could change `set(QT_MIN_VERSION "5.7.0")` to `set(QT_MIN_VERSION "5.6.0")` in the top-level CMakeLists.txt and see what happens. 

but I can assure you that we will not be porting autogen.py to python3

**Comment by dfaure-kdab** [comment]
Meanwhile Qt 5.9 is required for QNetworkRequest::NoLessSafeRedirectPolicy.

But the point remains that autogen.py+qmake are being phased out in favour of CMake.
