### ISSUE TITLE
Error when generating headers files from ws-discovery.wsdl

### ISSUE THREAD

**Issue by NicolasBernard456** [KDAB/KDSoap#242]
Hello,

Thanks for your awesome library!

I am trying to generate headers using kdwsdl2cpp from http://schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.wsdl.

This is the output i get:

Downloading 'http://schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.wsdl'
Download successful
importing schema at http://schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.xsd
Downloading 'http://schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.xsd'
Download successful
importing schema at http://schemas.xmlsoap.org/ws/2004/08/addressing
Downloading 'http://schemas.xmlsoap.org/ws/2004/08/addressing'
Download successful
Error[2:2] unexpected character
Element not found: "http://schemas.xmlsoap.org/ws/2004/08/addressing" "EndpointReference"
"http://www.w3.org/2001/XMLSchema" "schema"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Hello"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Bye"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Probe"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "ProbeMatches"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Resolve"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "ResolveMatches"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Types"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Scopes"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "XAddrs"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "MetadataVersion"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "SupportedMatchingRules"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Security"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "Sig"
"http://schemas.xmlsoap.org/ws/2005/04/discovery" "AppSequence"

I built KDSoap from git and i'm using Windows 10 and MingW 8.1.

Thanks for your response.

**Comment by dfaure-kdab** [comment]
I was on vacations last week. You found the problem meanwhile?

**Comment by NicolasBernard456** [comment]
Yes I actually did not need this wsdl. The Oasis wsdl ( http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-wsdl-os.wsdl) is enough to perform Ws Discovery.
