### ISSUE TITLE
autogen.py fails on windows (no module named cpack)

### ISSUE THREAD

**Issue by bornschein** [KDAB/KDSoap#25]
I am doing this:

git clone https://github.com/KDAB/KDSoap.git
cd KDSoap
git submodule update --init
set PATH=%PATH%;C:\Qt\qt-5.0.1\qtbase\bin
autogen.py

... and get the following error trace:

Traceback (most recent call last):
  File "C:\Qt\KDSoap\autogen.py", line 2, in <module>
    from autogen.autogen import autogen
  File "C:\Qt\KDSoap\autogen\autogen.py", line 3, in <module>
    from cpack import CPackGenerateConfiguration
ImportError: No module named 'cpack'

**Comment by Chadster766** [comment]
This is happening on a Debian Linux dev platform if I checkout any of the tags but not if I build trunk.

Should I run trunk? I don't normally do that for development.
