### ISSUE TITLE
Broken CMake config files

### ISSUE THREAD

**Issue by MehdiChinoune** [KDAB/KDSoap#258]
```
1> [CMake] CMake Error at E:/Lily/test/installed/x64-windows/share/KDSoap-qt6/KDSoapTargets.cmake:60 (set_target_properties):
1> [CMake]   The link interface of target "KDSoap::kdsoap" contains:
1> [CMake] 
1> [CMake]     Qt6::Core
1> [CMake] 
1> [CMake]   but the target was not found.  Possible reasons include:
1> [CMake] 
1> [CMake]     * There is a typo in the target name.
1> [CMake]     * A find_package call is missing for an IMPORTED target.
1> [CMake]     * An ALIAS target is missing.
```
Some suggested to add `find_dependency(Qt6Core)` in https://github.com/microsoft/vcpkg/pull/30371#issuecomment-1482544493

**Comment by dg0yt** [comment]
Note: This is for static linkage.

**Comment by dfaure-kdab** [comment]
We could certainly add that, but I'd like to make sure I understand the issue. How can you have an executable that (statically) links to KDSoap without the executable itself using Qt? All of the KDSoap API uses Qt. Having your exe magically link to Qt via KDSoap feels weird, the exe would almost for sure need Qt even if it wasn't using KDSoap.

I understand this is "as part of vcpkg packaging" which is not the typical use case, but still, am I right that this happens while attempting to define an executable that links to KDSoap? Or is there another case where KDSoapTargets.cmake is being used?

**Comment by MehdiChinoune** [comment]
> We could certainly add that, but I'd like to make sure I understand the issue. How can you have an executable that (statically) links to KDSoap without the executable itself using Qt? All of the KDSoap API uses Qt. Having your exe magically link to Qt via KDSoap feels weird, the exe would almost for sure need Qt even if it wasn't using KDSoap.
> 
> I understand this is "as part of vcpkg packaging" which is not the typical use case, but still, am I right that this happens while attempting to define an executable that links to KDSoap? Or is there another case where KDSoapTargets.cmake is being used?

If you search for KDSoap in a CMake file before searching for Qt5, The configuration will fail.
Of course anyone using KDSoap is using Qt but just to not let configuration fails in that case.
