### ISSUE TITLE
Co-installability of Qt5 and Qt6 version

### ISSUE THREAD

**Issue by tcberner** [KDAB/KDSoap#262]
Moin moin 

It would be great if KDSoap would be co-installable for both Qt5 and Qt6. 

It seems all files are suffixed appropriatly (or only present in one of the bindings) apart from the header files. Their co-installability was reverted in https://github.com/KDAB/KDSoap/commit/d2a04a2 .

Are there any plans to mitigate this issue, or how are consumers supposed to handle this as more and more, but not all, software moves to Qt6.

mfg Tobias

**Comment by dfaure-kdab** [comment]
One solution would be to install into KDSoap-Qt6/KDSoapClient/*.h and have KDSoap-Qt6 in the -I paths (easy with cmake). Then the includes would work for finding the headers in-source as well.

**Comment by a17r** [comment]
Any progress here?
