### ISSUE TITLE
Occasional getting an assert when writing data.

### ISSUE THREAD

**Issue by jtjbrady** [KDAB/KDSoap#264]
I'm occasionally hitting the assert on line 463 of KDSoapServerSocket.cpp, not sure what is causing it.
After adding a little debug, i.e. changing the line to:

`Q_ASSERT_X(written == httpHeaders.size(), "writeXML", qPrintable(QStringLiteral("Only wrote %1 of %2 bytes").arg(written).arg(httpHeaders.size()))); // Please report a bug if you hit this.`

I'm getting:
ASSERT failure in writeXML: "Only wrote -1 of 64 bytes", file...

**Comment by dfaure-kdab** [comment]
QIODevice::write returns -1 when an error occured. My first guess would be that the socket got closed meanwhile (i.e. the client went away, possibly). One way to make sure would be to output the errorString() of the socket (`this`).

**Comment by jtjbrady** [comment]
That is indeed the most likely cause.  I'll add errorString() to the assert to see what gets reported.

However, I'm seeing this occur maybe one a month, so it might take a while for me to confirm.

**Comment by jtjbrady** [comment]
Took nearly two months for this to pop up again, but yes I can confirm that this assert occured because the socket was closed.

**Comment by jtjbrady** [comment]
Doesn't happen for two months, then two come along at once.  The text from the assert this time was:
ASSERT failure in writeXML: "Only wrote -1 of 65 bytes - The remote host closed the connection", file ...

From my point of view I'm simply going to disable the two asserts in this function, I only reported them because "Please report a bug if you hit this."

**Comment by dfaure-kdab** [comment]
Thanks for this information. I'll turn the assert into a qWarning.
