### ISSUE TITLE
Inaccurate error message (line 37) in CMakeLists.txt for KDSoap 2.2.0 release

### ISSUE THREAD

**Issue by Cyb3rR4bb1t** [KDAB/KDSoap#298]
Hello,\
recently I downloaded the source of `KDSoap 2.2.0` from releases.\
Then attempted to build it, but an error occurred when using `cmake` in command line.\
Eventually I solved this issue.

## Problem
CMakeLists.txt - line 37:
```
FATAL_ERROR "Please do git submodule update --init --recursive"
```

## Failed fix attempt
Calling `git submodule update --init --recursive` results in an error indicating the source code is not a git repository.

## Reason
The error occurs, because `KDSoap 2.2.0` is dependent on `libkode` library, which is not present in the release.\
In order to build KDSoap, the source code of `libkode` library should be inside `kdwsdl2cpp/libkode` directory.

## Fix
Get the source code of `libkode` and place it in directory `<Your_KDSoap_Directory>/kdwsdl2cpp/libkode`
```
cd kdwsdl2cpp
git clone https://github.com/cornelius/libkode.git
```

**Comment by iamsergio** [comment]
The correct tarball is https://github.com/KDAB/KDSoap/releases/download/kdsoap-2.2.0/kdsoap-2.2.0.tar.gz it includes submodules.

GitHub automatically also uploads another tarball without it, which we can't delete unfortunately
