### ISSUE TITLE
Qt KDSoapServer and KDSoapServerObjectInterface Coexistence 

### ISSUE THREAD

**Issue by Chadster766** [KDAB/KDSoap#59]
I'm trying to get signals to a QML UI to work.

When the soap client sends a soap request to the KDSoapServer I have a signal being sent to the QML UI.

The problem is the KDSoapServer created by createServerObject doesn't seem to be able to send the signal to the QML UI.

I have a "apiserver" class that inherits the wsdl generated class and implements KDSoapServerObjectInterface. This class has the signals added to it's header file.

I couldn't add the KDSoapServer to the context directly but if I used multiple inheritance of both apiserver and KDSoapServer. This allowed me to add the apiserver class to the context and create the KDSoapServer as well.

With the multiple inheritance the QML UI can call a slot and if the slot calls a signal the QML UI receives it but the signals fail if called in a wsdl function.

**Comment by Chadster766** [comment]
This would be possible\easier if Qt supported multiple inheritance of QObject more that once.

**Comment by dfaure-kdab** [comment]
SOAP servers are meant to be implemented in C++, not in QML. I'm surprised by the idea of implementing servers in QML, which is a language for user interfaces.

Anyhow, you could just add both objects to the context, with different names; no need for multiple inheritance.

**Comment by Chadster766** [comment]
You can bridge the QML UI with C++ via Signals and Slots through the QObject base and adding it to the QmlApplicationViewer context as shown in the example below:

```
QmlApplicationViewer viewer;

QDeclarativeContext *context = viewer.rootContext();

vmodbus *modbus = new vmodbus();
context->setContextProperty("modbus", modbus);
```

Since I implemented the KDSoapServer using the below code:

```
class Server : public KDSoapServer {
public:
    QObject* createServerObject() {
        return new APIServer;
    }
};
```
All though you can add the KDSoapServer to the context:
```
Server server;
server.setLogLevel(Server::LogEveryCall);

context->setContextProperty("apicomms", &server);
```
Any Signals and Slots declared in the APIServer class for QML UI communication are not available because of the Server class's base is KDSoapServer not APIServer.

As a workaround I created a communication class that does the communications between the APIServer, KDSoapServer and the QML UI. This added layer of communications is highly redundant and even with only four function hard to understand.

**Comment by tokoe-kdab** [comment]
Hej Chad,

I think you misuse the API here... you are not supposed to call KDSoapServer::createServerObject yourself and access the created object. Instead you should just provide a custom implementation of the KDSoapServerObjectInterface interface and return it. And inside the KDSoapServerObjectInterface::processRequest() you do the actual work...
I don't see any reason why that should happen in QML. Instead the processRequest() implementation can communicate with a standalone controller object, which itself is exported to QML (I guess that is what you mean with your workaround). And no, this additional layer is not redundant, this abstraction between business logic and UI is exactly what makes QML such a great and flexible language.
