### ISSUE TITLE
error in installation : ImportError: cannot import name ForwardHeaderGenerator

### ISSUE THREAD

**Issue by latyyfa** [KDAB/KDSoap#65]
I'm running python 2.7.5 on Ubuntu 14.04
I'm trying to install the library KD Soap  and I get this error : 

user@server:/path/KDSoap-master/autogen$ python autogen.py 
Traceback (most recent call last):
  File "autogen.py", line 11, in <module>
    from header import ForwardHeaderGenerator
  File "/path/KDSoap-master/autogen/header.py", line 6, in <module>
    import autogen
  File "/path/KDSoap-master/autogen/autogen.py", line 11, in <module>
    from header import ForwardHeaderGenerator
ImportError: cannot import name ForwardHeaderGenerator

**Comment by winterz** [comment]
do you get the same error if you run it from the top-level source or from a builddir?

**Comment by latyyfa** [comment]
I solved the problem by cloning the source instead of downloading the zip file !!
