### ISSUE TITLE
nil boolean of member is true, although member is not nil

### ISSUE THREAD

**Issue by wuarmin** [KDAB/KDSoap#72]
Hello,

I use code-gen of KDSoap. 
Today I recognized, that there are tags missing in the soap-request (The request fails because of the missing tags). The error occurs, cause I want to use a part of the returnval of response1 in request2.

So it seems that the copy-constructor of some items does not work properly. Can you help me?

thanks

**Comment by dfaure-kdab** [comment]
Are you using KDSoap from git master, to make sure you're not hitting a bug that's already fixed?

If so, can you make a testcase of the issue, ideally in the form of a unittest?

Is the WSDL file that you're using, public? (so we can add it to our unittests)

**Comment by wuarmin** [comment]
I use a version from November 2014. Today I cloned the git master repo, but there occurs the problem, that no requests are sent to Server. i couldn't figure out why, so far. so I changed back to the working version. 
The wsdl is not public. Do you want to see it?

**Comment by wuarmin** [comment]
So, no I'm using the latest version and it works, but the error is still there.
soap example:
<father>
   <child_name1>john</child_name1>
   <child_name2>doe</child_name2>
</father>

The father-objects member d_ptr->father_nil returns true, although the sub-objects child_name1 and child_name2 aren't nil. The nil-members of them returns false. 
So in serialization the father-node droups out, and this should not happen. 

If I have more time, a can produce an unit-test. Or do you have an explanation?

thanks

**Comment by dfaure-kdab** [comment]
This looks related to commit fc9d00b05cb39d20f33c47e4820bcb4ee8b7ffbb which fixed this for some cases, but indeed it seems to be missing in case deserialize() is called (thanks for the line numbers in converter_complextype.cpp, this made the bug easy to find).

An extension of test_tech3356.cpp to check for this case would be excellent indeed.

Can you check if this patch fixes the issue? http://kdab.com/~dfaure/2015/github-72-fix.diff

**Comment by wuarmin** [comment]
Indeed! 
This patch fixes the issue. Thank you Mr. Faure for the fast fix!
I like your project!

**Comment by dfaure-kdab** [comment]
Thanks for the test and the kind words. Pushed in commit 37b8750e550eec8e334c5aba7a09dae544589aa3
