### ISSUE TITLE
Dependency on QtGui

### ISSUE THREAD

**Issue by vitorboschi** [KDAB/KDSoap#73]
It looks like KDSoap depends on QtGui, which doesn't seem necessary to me. If possible, could this dependency be lifted? Which functionality depends on it?

**Comment by dfaure-kdab** [comment]
You should be able to compile the KDSoap libraries without QtGUI, it's only the GUI example programs that need it, you can disable the "examples" subdir.

**Comment by vitorboschi** [comment]
The problem is that the library itself is linked against QtGui

**Comment by dfaure-kdab** [comment]
Yes, and you can easily adjust that: if you use qmake, add QT -= gui to the .pro file of the library, and tell me if it works for you so I can merge that.

**Comment by vitorboschi** [comment]
Ah, that's great. I'll try it and report back

**Comment by winterz** [comment]
fixed in the CMake buildsystem.  All references to QtGUI are gone except where needed by a couple examples.
commit 6c3525d783b9d0249002b1a9b7799cb2a791da71

**Comment by vitorboschi** [comment]
@winterz it's working fine now. I guess this issue can be closed.

Thank you guys for the great support :)

**Comment by dfaure-kdab** [comment]
Ah, you are using the cmake buildsystem, not the qmake one?
(we should still fix this in the qmake buildsystem)

**Comment by vitorboschi** [comment]
yes, I'm using CMake. However, I did a test build using qmake  and the generated binary doesn't link to QtGui, so it looks like the problem was only in the CMake build.
Please note that I only tested them in Qt4, so I can't comment on the build using Qt5

**Comment by dfaure-kdab** [comment]
Oh, you are right, the kdsoap library has had QT -= gui ever since I wrote the very first pro file in 2009 :-) So this was only a problem in the cmake buildsystem. Closing then.
