### ISSUE TITLE
kdwsdl2cpp error ONVIF tt:ReferenceToken

### ISSUE THREAD

**Issue by TimKes** [KDAB/KDSoap#76]
Hey guys,
I recently started using KDSoap and kdwsdl2cpp and I'm really excited with seeing what it does. However, I'm getting some problems when trying to convert certain .wsdl's. 
The following problems occurs to me when I try to convert the ImagingBinding wsdl from ONVIF: 
http://www.onvif.org/Documents/Specifications.aspx
http://www.onvif.org/onvif/ver20/imaging/wsdl/imaging.wsdl

> kdwsdl2cpp -o imaging.h imaging.wsdl
> importing schema at /schema/onvif.xsd
> Downloading '/schema/onvif.xsd'
> QSslSocket: cannot resolve TLSv1_1_client_method
> QSslSocket: cannot resolve TLSv1_2_client_method
> QSslSocket: cannot resolve TLSv1_1_server_method
> QSslSocket: cannot resolve TLSv1_2_server_method
> QSslSocket: cannot resolve SSL_select_next_proto
> QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
> QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
> Error downloading '/schema/onvif.xsd': Protocol "" is unknown
> No service tag found in the wsdl file, generating one service per binding
> Converting 0 simple types
> Converting 17 complex types
> ERROR: basic type not found: "tt:ReferenceToken"
> ASSERT: "!typeName.isEmpty()" in file ../kdwsdl2cpp/src/converter_complextype.cpp, line 146
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

Similar ONVIF WSDL's give the same problem at the tt:ReferenceToken. 
I'm pretty new to all of this, so I may have done something which made it work different which may have to do with this issue:
On line 14 in imaging.wsdl, I changed schemaLocation to "/schema/onvif.xsd". I have a local copy of this on my harddrive at this path location. Without this, I would get an error about not being able to find schema.

After reading up on it some more, I get the feeling that the importing of schema's is where it's going wrong. This leads to my question: Does kdwsdl2cpp support external schema's, or do I have to rework all schema's that are being called to be physically present in the wsdl?

**Comment by TimKes** [comment]
The reason why I changed the path to "/schema/onvif.xsd" from "schemaLocation="../../../ver10/schema/onvif.xsd" @ line 14 as described above is this:

>kdwsdl2cpp -o imaging.h imaging.wsdl 
importing schema at file:///C:/Users/Marco/ver10/schema/onvif.xsd
Unable to open file C:/Users/Marco/ver10/schema/onvif.xsd
No service tag found in the wsdl file, generating one service per binding
Converting 0 simple types
Converting 17 complex types
ERROR: basic type not found: "tt:ReferenceToken"
ASSERT: "!typeName.isEmpty()" in file ../kdwsdl2cpp/src/converter_complextype.cpp, line 146

This leads me to think that the external schema is indeed not loaded. Having the local copy does change the result, but not entirely.
Note that other ONVIF WSDL's are converting correctly with the schemaLocation change. However, each WSDL that contains a tt:ReferenceToken seems to have trouble.

**Comment by dfaure-kdab** [comment]
Yes, neither of these URLs are usable by KDSoap (QNetworkAccessManager).
'/schema/onvif.xsd' looks like an absolute path, but I doubt you have a /schema on your harddisk ;)
And C:/Users/Marco/... doesn't seem to exist either.

While kdwsdl2cpp does support downloading schemas with a full http url, network activity during compilation is not ideal, so I indeed recommend downloading all files locally and adjusting the paths to be relative in the wsdl and xsd files. (e.g. just schemLocation="onvif.xsd").

You can see an example of that (with another onvif wsdl file) in unittests/onvif.org.

**Comment by TimKes** [comment]
Thanks for the quick response.
However, I think I found the real issue.
In front of the "schemaLocation" parameter, the parameter "namespace" is set to "http://www.onvif.org/ver10/schema". However, this variable seem to be ignored. Rewriting the "schemaLocation" to the full path ('http://www.onvif.org/ver10/schema/onvif.xsd") has fixed my problem.

**Comment by dfaure-kdab** [comment]
A namespace is just a string (used to separate schemas to avoid conflicts), it is not the base for relative URLs.

The base for schemaLocation="../../../ver10/schema/onvif.xsd" was the URL of the wsdl file itself, but after a local download this obviously doesn't work anymore.

Rewriting schemaLocation to be a full URL is indeed a solution (but it will trigger a download on every build), so I suggest rewriting it to a relative path to a local file (schemaLocation="onvif.xsd") instead.

**Comment by dfaure-kdab** [comment]
I think this is issue is resolved, so I'm closing it, feel free to reopen if you think there's still something to be fixed.
