### ISSUE TITLE
Network connection 

### ISSUE THREAD

**Issue by lolopoloskos** [KDAB/KDSoap#78]
If disable Network Connection or go to Sleep, KDSoap loss connection.
After enable Network, I try call SOAP method and KDSoap dont work correctly.

This bug found on Windows 7

**Comment by Knarf64** [comment]
Hi ! 

Thanks for the report, as far as I understand, we do not do anything fancy network wise, so this kind of issue might be directly related to qt behavior. If you could give us a back trace or more information it could be useful but I think you should have a look on the Qt side to confirm my doubts. 

Cheers.

**Comment by lolopoloskos** [comment]
Ok, I check
It not problem in KDSoap..
Sorry..
It on the Qt side
