### ISSUE TITLE
Missing entry in KDSoapServerObjectInterface::doneProcessingRequestWithPath

### ISSUE THREAD

**Issue by pcipriano** [KDAB/KDSoap#80]
The method KDSoapServerObjectInterface::doneProcessingRequestWithPath is missing an entry to copy the m_detailValue to the current object from the other interface passed in.

Something along the lines:
```C++
d->m_detail = otherInterface.d->m_detail;
d->m_detailValue = otherInterface.d->m_detailValue;    //Missing entry
d->m_responseHeaders = otherInterface.d->m_responseHeaders;
```

**Comment by dfaure** [comment]
Thanks, fix applied in c9be6ef.
