### ISSUE TITLE
Soap faults incorrect namespace

### ISSUE THREAD

**Issue by pcipriano** [KDAB/KDSoap#81]
Hi,

I've been having some issues with interoperability between different Soap frameworks when Soap faults are emitted from our KDSoap server. I found the issue to be the Fault element inside the Body does not have the correct namespace.

Other frameworks build a fault like this:

``` xml
<soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <soap:Fault>
          <!-- fault contents -->
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

KDSoap will build it like this:

``` xml
<soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <n1:Fault xmlns:n1="my custom namespace">
          <!-- fault contents -->
      </n1:Fault>
   </soap:Body>
</soap:Envelope>
```

Looking at http://schemas.xmlsoap.org/soap/envelope/ the Fault element should definitely be inside that namespace.

For now I've fixed it by detecting the fault case in KDSoapMessageWriter::messageToXml and writing the appropriate namespace.

**Comment by dfaure-kdab** [comment]
Can you submit the fix as a patch or merge request so I can see what you mean exactly ?
Ideally you could submit a unit-test too :)

**Comment by dfaure-kdab** [comment]
I just pushed some fixes related to namespaces of Body elements, can you check if this still happens?

**Comment by SudakovIvan** [comment]
This still happens. I'll submit a merge request soon
