### ISSUE TITLE
build against qt 5.7 fails

### ISSUE THREAD

**Issue by drakkan** [KDAB/KDSoap#84]
Please try to build against qt 5.7.0, I have these errors with both 1.5.1 and git master

./configure.sh -release -shared -prefix /usr 
KD Soap v1.5.50 configuration:
  Install Prefix.............: /usr
    (default: /usr/local/KDAB/KDSoap-1.5.50)
  Debug......................: no (default: no)
  Release....................: yes (default: yes)
  Shared build...............: yes (default: yes)
  Compiled-In Unit Tests.....: no (default: no)
  Restricted symbol export
    (shared build only)......: yes (default: yes)

Project MESSAGE: Install prefix is /usr
Project MESSAGE: This is KD Soap version 1.5.50
Reading /tmp/KDSoap/kdwsdl2cpp/kdwsdl2cpp.pro
 Reading /tmp/KDSoap/kdwsdl2cpp/libkode/libkode.pro
 Reading /tmp/KDSoap/kdwsdl2cpp/common/common.pro
 Reading /tmp/KDSoap/kdwsdl2cpp/schema/schema.pro
 Reading /tmp/KDSoap/kdwsdl2cpp/wsdl/wsdl.pro
 Reading /tmp/KDSoap/kdwsdl2cpp/src/src.pro
Reading /tmp/KDSoap/src/src.pro
 Reading /tmp/KDSoap/src/KDSoapClient/KDSoapClient.pro
 Reading /tmp/KDSoap/src/KDSoapServer/KDSoapServer.pro
Reading /tmp/KDSoap/features/features.pro
Reading /tmp/KDSoap/include/include.pro
 Reading /tmp/KDSoap/include/KDSoapClient/KDSoapClient.pro
 Reading /tmp/KDSoap/include/KDSoapServer/KDSoapServer.pro
Reading /tmp/KDSoap/examples/examples.pro
 Reading /tmp/KDSoap/examples/helloworld_client/helloworld_client.pro
 Reading /tmp/KDSoap/examples/helloworld_server/helloworld_server.pro
 Reading /tmp/KDSoap/examples/holidays_sync/holidays_sync.pro
 Reading /tmp/KDSoap/examples/holidays_gui/holidays_gui.pro
 Reading /tmp/KDSoap/examples/holidays_wsdl/holidays_wsdl.pro
Ok, now run make, then make install to install into /usr

make
cd kdwsdl2cpp/ && ( test -e Makefile || /usr/lib/qt/bin/qmake /tmp/KDSoap/kdwsdl2cpp/kdwsdl2cpp.pro VERSION=1.5.50 CONFIG+=kdsoap_target CONFIG+=release CONFIG-=debug CONFIG-=debug_and_release CONFIG+=hide_symbols CONFIG-=static CONFIG-=staticlib CONFIG+=shared KDSOAP_INSTALL_PREFIX=/usr KDSOAP_BASE=/tmp/KDSoap -o Makefile ) && make -f Makefile 
make[1]: ingresso nella directory "/tmp/KDSoap/kdwsdl2cpp"
cd libkode/ && ( test -e Makefile || /usr/lib/qt/bin/qmake /tmp/KDSoap/kdwsdl2cpp/libkode/libkode.pro VERSION=1.5.50 CONFIG+=kdsoap_target CONFIG+=release CONFIG-=debug CONFIG-=debug_and_release CONFIG+=hide_symbols CONFIG-=static CONFIG-=staticlib CONFIG+=shared KDSOAP_INSTALL_PREFIX=/usr KDSOAP_BASE=/tmp/KDSoap -o Makefile ) && make -f Makefile 
make[2]: ingresso nella directory "/tmp/KDSoap/kdwsdl2cpp/libkode"
g++ -c -pipe -Wno-long-long -ansi -pedantic -Wnon-virtual-dtor -Wundef -Wcast-align -Wchar-subscripts -Wpointer-arith -Wwrite-strings -Wformat -Wformat-security -Wmissing-format-attribute -Woverloaded-virtual -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -W -D_REENTRANT -fvisibility=hidden -fvisibility-inlines-hidden -DUSE_EXCEPTIONS -DQT_FATAL_ASSERT -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../kdwsdl2cpp -isystem /usr/include/qt -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I.moc -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/code.o code.cpp
In file included from /usr/include/qt/QtCore/qatomic.h:46:0,
                 from /usr/include/qt/QtCore/qglobal.h:1145,
                 from /usr/include/qt/QtCore/qalgorithms.h:43,
                 from /usr/include/qt/QtCore/qlist.h:43,
                 from /usr/include/qt/QtCore/qstringlist.h:41,
                 from /usr/include/qt/QtCore/QStringList:1,
                 from code.cpp:22:
/usr/include/qt/QtCore/qbasicatomic.h:61:4: error: #error "Qt requires C++11 support"
 #  error "Qt requires C++11 support"
    ^~~~~
In file included from /usr/include/qt/QtCore/qalgorithms.h:43:0,
                 from /usr/include/qt/QtCore/qlist.h:43,
                 from /usr/include/qt/QtCore/qstringlist.h:41,
                 from /usr/include/qt/QtCore/QStringList:1,
                 from code.cpp:22:
/usr/include/qt/QtCore/qglobal.h:1133:23: error: expected ‘,’ or ‘...’ before ‘&&’ token
 void qAsConst(const T &&) Q_DECL_EQ_DELETE;
.......

I'm building on archlinux with gcc 6.1.1

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160602 (GCC)

**Comment by drakkan** [comment]
the build issue is caused from the -ansi CFLAGS here:

https://github.com/KDAB/KDSoap/blob/master/g%2B%2B.pri#L2

this CFLAGS should not be used with qt >= 5.7

**Comment by dfaure-kdab** [comment]
Thanks for the fix, applied.

**Comment by drakkan** [comment]
Thanks, maybe a new release is needed, meantime I fixed the archlinux package using some sed magic

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kdsoap#n19
