### ISSUE TITLE
KDSoapClientInterface::call might block forever if connection is lost

### ISSUE THREAD

**Issue by ekandler** [KDAB/KDSoap#88]
Starting a blocking KDSoap call without proper network connection returns an empty Object when deserialized - as expected.
However, when the network connection gets broken during a request for longer than 2 minutes the call blocks forever, regardless of whether the network is connected again or not.
This behaviour occurs about every 2nd time using Qt 5.6.1-1 and Ubuntu 14.04.4.

In the cases where it doesn't block forever, it blocks until the connection is back, returns an empty object once, and then continues normally.

Could this be a problem with the used system? Or would a timeout within KDSoap be a good idea?

**Comment by dfaure** [comment]
I suspect this to be a QNetworkAccessManager bug, KDSoap is merely listening to its signals.

Can you try with a QNAM testcase doing the same HTTP call, and seeing if you get the finished() signals from QNetworkReply ?

**Comment by ekandler** [comment]
Thank you for the quick reply.

Indeed this seems to be related with QNetworkAccessManager. When disconnecting, QNetworkReply::finished never gets called - also for new requests. When reconnecting new requests get processed normally, but the 'old' requests are lost.
In some cases QNetworkReply::error gets emitted, but not for every submitted request.

Despite this being a problem with QNetworkAccessManager, do you think a timeout for the request in KDSoap would be a bad thing?

**Comment by relgukxilef** [comment]
Given that there isn't a way to set a timeout for `QNetworkRequest` (https://bugreports.qt.io/browse/QTBUG-3443) it might actually be the intended behaviour. 
My suggestion would be to start a `QTimer` and connect it to `QNetworkReply::abort`.

**Comment by dfaure** [comment]
OK, I would accept such a patch.

(if I do it myself I'd rather fix it in Qt first :-)

**Comment by ekandler** [comment]
I did some experiments with the suggestion of @relgukxilef and set up a `QTimer` in `KDSoapThreadTask` that gets started in `KDSoapThreadTask::process` as you can see [here](https://gist.github.com/ekandler/3cb619e4414dc3e2781c8c1987fe5fa3).
The timeout can be specified via `KDSoapClientInterface::setTimeout`.

When the connection is lost, `QNetworkReply::abort` gets called after the specified time, which also emits the `QNetworkReply::finished()` signal. So, an empty object gets returned from the soap request.

However, when I continue to send soap requests without network connection, and then reconnecting the network, the next soap request - that should work again normally - causes a segfault. Also it looks like the debugger can't produce a proper stacktrace, because it contains more than 9000 entries with `??`.

Regarding the made changes, I cannot determine what could cause the problem. Do you have any idea how this could happen?

**Comment by dfaure-kdab** [comment]
After further investigation, I just implemented a timer in KDSoap, see commit cf6885c.
