### ISSUE TITLE
Parsing reply before it finished!

### ISSUE THREAD

**Issue by lolopoloskos** [KDAB/KDSoap#90]
In source code [https://github.com/KDAB/KDSoap/blob/master/src/KDSoapClient/KDSoapPendingCall.cpp](url) I saw that if reply didn't finished it not parsed again because 

```
    if (parsed) {
        return;
    }
    parsed = true;
```

In my project I change that

```
    if (!reply->isFinished()) {
        qWarning("KDSoap: Parsing reply before it finished!");
    }
```

to 

```
    if (!reply->isFinished()) {
        qWarning("KDSoap: Parsing reply before it finished!");
        parsed = false; return;
    }
```

but before pull request I don't understand why KDSoapPendingCall::Private::parseReply called twice (returnMessage, returnHeaders)

**Comment by dfaure** [comment]
OK, similar fix pushed in 62e1c67.

The real question is, why do you hit the warning about parsing before finished. Are you calling 
returnMessage, returnHeaders or returnValue before the call has finished ()? This seems like incorrect API usage.

**Comment by lolopoloskos** [comment]
Hmm.. No, I dont call return* function before. I call it in SLOT

`connect(myJob, SIGNAL(finished(KDSoapJob*)), this, SLOT(onMyJobDone(KDSoapJob*)));`

**Comment by lolopoloskos** [comment]
Ok, I reproduce this error.. And as I tell before, I don't call return* method before signal finished

You can reproduce this error too.. 
You have to disconnect your lan cable and connect to wi-fi.. after that connect your lan cable and disable wi-fi and you can see that all Soap Jobs doesn't finished, but signal finished generated.

**Comment by dfaure-kdab** [comment]
I just fixed the fact that isFinished() is false (when we don't have network access), which led to this warning from KDSoap, it was in fact a bug in Qt. https://codereview.qt-project.org/223523
