### ISSUE TITLE
SOAP reply doesn't contain child values present in message

### ISSUE THREAD

**Issue by cjh1** [KDAB/KDSoap#95]
We are seeing the server return the following response:

```xml
"<?xml version=\"1.0\" encoding=\"utf-8\"?><soapenv:Envelope xmlns:soapenv=\"htt
p://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLS
chema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><soapenv:Body><n
s1:getStreamingFileUploadURLResponse soapenv:encodingStyle=\"http://schemas.xmls
oap.org/soap/encoding/\" xmlns:ns1=\"https://www.uit.hpc.mil/UITAPIv3/uitapi.jws
\"><getStreamingFileUploadURLReturn xsi:type=\"xsd:string\">https://www.uit.hpc.
mil/UITAPIv3/StreamingFileUploadServlet</getStreamingFileUploadURLReturn></ns1:g
etStreamingFileUploadURLResponse></soapenv:Body></soapenv:Envelope>"
```

Our code tries to pull out a child element:

```cpp
auto response = job->reply()
response.childValues()
         .child(QLatin1String("getStreamingFileUploadURLReturn"))
         .value().value<QString>();
```

Further debugging shows that there are no childValues().

**Comment by cjh1** [comment]
Note this worked for us with version 1.3

**Comment by cjh1** [comment]
So I have done some more digging and it looks like the behavior of childValues() has change. I wrote a [test case](https://github.com/cjh1/KDSoap/blob/uit-debug/unittests/uitapi/test_uitapi.cpp#L87-L110) that uses the XML returned by the server. The output looks like;

```
21: QDEBUG : UitapiRPCTest::testGetStreamingFileUploadURLJob()  "getStreamingFileUploadURLReturn" QVariant(QString, "https://www.uit.hpc.mil/UITAPIv3/StreamingFileUploadServlet")
21: QDEBUG : UitapiRPCTest::testGetStreamingFileUploadURLJob() ()
21: QDEBUG : UitapiRPCTest::testGetStreamingFileUploadURLJob() "https://www.uit.hpc.mil/UITAPIv3/StreamingFileUploadServlet"
21: PASS   : UitapiRPCTest::testGetStreamingFileUploadURLJob()
```

Notice the middle QDEBUG statement prints () the return value from childValues().

**Comment by cjh1** [comment]
So are the returns no longer considered child values?

**Comment by dfaure-kdab** [comment]
Yes KDSoap makes an effort at hiding the RPC-style-specific wrappers, to make it all look like actual RPC: conceptually, you are making a method call with arguments, and getting a return value, which is that string. The fact that the string is wrapped into an XML element is an implementation detail of RPC-style SOAP, you shouldn't have to deal with that, so this is indeed a bugfix between 1.3 and current.

**Comment by cjh1** [comment]
@dfaure-kdab Thanks for confirming the change, we will make the necessary changes.
