### ISSUE TITLE
QtWidgets imposed by some examples and no way to bypass it

### ISSUE THREAD

**Issue by WilliamTambellini** [KDAB/KDSoap#96]
At the moment QtWidgets is required just because of some examples (holidays_gui, ...).
Consequently, users not using/having Qt GUI, there is no way to build/compile kdsoap.
Expected  behavior: kdsoap build scripts to exclude some examples if QtWidgets not found.
In examples/CMakeLists.txt : remove  "REQUIRED" in find_package(Qt5Widgets REQUIRED)
and conditionally exclude or include the gui examples function to QtWidgtes found  or not.

**Comment by dfaure-kdab** [comment]
The idea makes sense. Can you provide a complete patch or merge request?

**Comment by WilliamTambellini** [comment]
Thanks David.
For some legal reasons, it's quite hard/long for me to release publicly any code sources I would write. 
Now, any thing like this would perhaps do the job:
if (Qt5Widgets_found) 
 add_subdirectory(helloworld_client)
 add_subdirectory(helloworld_server)
 add_subdirectory(holidays_gui)
endif() 
?
Cheers, WT.
