### ISSUE TITLE
holidays_sync example timed out

### ISSUE THREAD

**Issue by Massimo-B** [KDAB/KDSoap#99]
```
./holidays_sync 
Looking up the date of Valentine's Day in 2009...
Fault code 4: Socket operation timed out
```

This example isn't working currently. This is a proxied environment having http_proxy set. However I guess the service is not available anymore. Is there some working SOAP example with a public service available?

**Comment by dfaure-kdab** [comment]
Works for me (so either the server was down temporarily or the proxy is the issue).

Note that the kdsoap unittests include calls to other public services, see unittests/webcalls_wsdl (e.g. testOrteLookup). Thanks for the additional calc example that you found meanwhile, now added to unittests/calc.

**Comment by Massimo-B** [comment]
Ok, this was a web proxy issue blocking the request. Actually this is the same issue like
https://sourceforge.net/p/gsoap2/bugs/1115/
KDSoap could respect the http_proxy https_proxy and no_proxy environment settings in order to make the user configure the proxy later. Currently this can only be done outside of KDSoap by setting the QNetworkProxy.
